name: Generate TypeScript types

on:
  repository_dispatch:
    types: [openapi_spec_update]

jobs:
  generate_types:
    runs-on: self-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download OpenAPI Spec
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: generate-openapi-spec.yaml
          repo: OpusDNS/opusdns-api
          name: openapi-spec
          path: ./src/openapi.json
          github_token: ${{secrets.GH_PAT_OPENAPI_OPUSDNS_API}}

      - name: Install Dependencies
        run: npm install

      - name: Generate TypeScript Types
        run: npx openapi-typescript openapi.json -o src/schema.d.ts

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/openapi.json
          git add src/schema.d.ts
          git commit -m "Update OpenAPI spec and types"
          git push

